// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: users.proto

package grpcusers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserGet_Users_FullMethodName = "/users.UserGet/Users"
)

// UserGetClient is the client API for UserGet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserGetClient interface {
	Users(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*UsersReply, error)
}

type userGetClient struct {
	cc grpc.ClientConnInterface
}

func NewUserGetClient(cc grpc.ClientConnInterface) UserGetClient {
	return &userGetClient{cc}
}

func (c *userGetClient) Users(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*UsersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersReply)
	err := c.cc.Invoke(ctx, UserGet_Users_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGetServer is the server API for UserGet service.
// All implementations must embed UnimplementedUserGetServer
// for forward compatibility.
type UserGetServer interface {
	Users(context.Context, *EmptyParams) (*UsersReply, error)
	mustEmbedUnimplementedUserGetServer()
}

// UnimplementedUserGetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserGetServer struct{}

func (UnimplementedUserGetServer) Users(context.Context, *EmptyParams) (*UsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Users not implemented")
}
func (UnimplementedUserGetServer) mustEmbedUnimplementedUserGetServer() {}
func (UnimplementedUserGetServer) testEmbeddedByValue()                 {}

// UnsafeUserGetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserGetServer will
// result in compilation errors.
type UnsafeUserGetServer interface {
	mustEmbedUnimplementedUserGetServer()
}

func RegisterUserGetServer(s grpc.ServiceRegistrar, srv UserGetServer) {
	// If the following call pancis, it indicates UnimplementedUserGetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserGet_ServiceDesc, srv)
}

func _UserGet_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGetServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGet_Users_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGetServer).Users(ctx, req.(*EmptyParams))
	}
	return interceptor(ctx, in, info, handler)
}

// UserGet_ServiceDesc is the grpc.ServiceDesc for UserGet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserGet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserGet",
	HandlerType: (*UserGetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Users",
			Handler:    _UserGet_Users_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
